'use strict';

// ── Listas de palabras funcionales (ES/EN) ──
const FUNCTION_WORDS_ES = new Set([
    // Español
    'a', 'acá', 'ahí', 'al', 'algo', 'algunas', 'algunos', 'allá', 'allí',
    'ambos', 'ante', 'antes', 'aquel', 'aquella', 'aquellas', 'aquello',
    'aquellos', 'aquí', 'cada', 'como', 'con', 'contra', 'cual', 'cuales',
    'cuando', 'cuanto', 'cuanta', 'cuantos', 'cuantas', 'de', 'del', 'desde',
    'donde', 'dos', 'durante', 'e', 'el', 'él', 'ella', 'ellas', 'ello',
    'ellos', 'en', 'entre', 'era', 'erais', 'eran', 'eras', 'eres', 'es',
    'esa', 'esas', 'ese', 'eso', 'esos', 'esta', 'estaba', 'estabais',
    'estaban', 'estabas', 'estad', 'estada', 'estadas', 'estado', 'estados',
    'estamos', 'estando', 'estar', 'estaremos', 'estará', 'estarán',
    'estarás', 'estaré', 'estaréis', 'estaría', 'estaríais', 'estaríamos',
    'estarían', 'estarías', 'estas', 'este', 'estemos', 'esto', 'estos',
    'estoy', 'estuve', 'estuviera', 'estuvierais', 'estuvieran', 'estuvieras',
    'estuvieron', 'estuviese', 'estuvieseis', 'estuviesen', 'estuvieses',
    'estuvimos', 'estuviste', 'estuvisteis', 'estuviéramos', 'estuviésemos',
    'estuvo', 'está', 'estábamos', 'estáis', 'están', 'estás', 'esté',
    'estéis', 'estén', 'estés', 'fue', 'fuera', 'fuerais', 'fueran',
    'fueras', 'fueron', 'fuese', 'fueseis', 'fuesen', 'fueses', 'fui',
    'fuimos', 'fuiste', 'fuisteis', 'fuéramos', 'fuésemos', 'ha', 'habida',
    'habidas', 'habido', 'habidos', 'habiendo', 'habremos', 'habrá',
    'habrán', 'habrás', 'habré', 'habréis', 'habría', 'habríais',
    'habríamos', 'habrían', 'habrías', 'habéis', 'había', 'habíais',
    'habíamos', 'habían', 'habías', 'han', 'has', 'hasta', 'hay', 'haya',
    'hayamos', 'hayan', 'hayas', 'hayáis', 'he', 'hemos', 'hube', 'hubiera',
    'hubierais', 'hubieran', 'hubieras', 'hubieron', 'hubiese', 'hubieseis',
    'hubiesen', 'hubieses', 'hubimos', 'hubiste', 'hubisteis', 'hubiéramos',
    'hubiésemos', 'hubo', 'la', 'las', 'le', 'les', 'lo', 'los', 'más',
    'me', 'mi', 'mis', 'mucha', 'muchas', 'mucho', 'muchos', 'muy', 'mí',
    'mía', 'mías', 'mío', 'míos', 'nada', 'ni', 'no', 'nos', 'nosotras',
    'nosotros', 'nuestra', 'nuestras', 'nuestro', 'nuestros', 'o', 'os',
    'otra', 'otras', 'otro', 'otros', 'para', 'pero', 'poco', 'por',
    'porque', 'que', 'qué', 'quien', 'quienes', 'se', 'sea', 'seamos',
    'sean', 'seas', 'seremos', 'será', 'serán', 'serás', 'seré', 'seréis',
    'sería', 'seríais', 'seríamos', 'serían', 'serías', 'seáis', 'sido',
    'siendo', 'sin', 'sobre', 'sois', 'somos', 'son', 'soy', 'su', 'sus',
    'suya', 'suyas', 'suyo', 'suyos', 'sí', 'también', 'tanto', 'te',
    'tendremos', 'tendrá', 'tendrán', 'tendrás', 'tendré', 'tendréis',
    'tendría', 'tendríais', 'tendríamos', 'tendrían', 'tendrías', 'tened',
    'tenemos', 'tenga', 'tengamos', 'tengan', 'tengas', 'tengo', 'tengáis',
    'tenida', 'tenidas', 'tenido', 'tenidos', 'teniendo', 'tenéis', 'tenía',
    'teníais', 'teníamos', 'tenían', 'tenías', 'ti', 'tiene', 'tienen',
    'tienes', 'todo', 'todos', 'tu', 'tus', 'tuve', 'tuviera', 'tuvierais',
    'tuvieran', 'tuvieras', 'tuvieron', 'tuviese', 'tuvieseis', 'tuviesen',
    'tuvieses', 'tuvimos', 'tuviste', 'tuvisteis', 'tuviéramos',
    'tuviésemos', 'tuvo', 'tuya', 'tuyas', 'tuyo', 'tuyos', 'tú', 'un',
    'una', 'uno', 'unos', 'vosotras', 'vosotros', 'vuestra', 'vuestras',
    'vuestro', 'vuestros', 'y', 'ya', 'yo'
]);

const FUNCTION_WORDS_EN = new Set([
    // English
    'a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an',
    'and', 'any', 'are', 'as', 'at', 'be', 'because', 'been', 'before',
    'being', 'below', 'between', 'both', 'but', 'by', 'can', 'could', 'did',
    'do', 'does', 'doing', 'down', 'during', 'each', 'few', 'for', 'from',
    'further', 'had', 'has', 'have', 'having', 'he', 'her', 'here', 'hers',
    'herself', 'him', 'himself', 'his', 'how', 'i', 'if', 'in', 'into',
    'is', 'it', 'its', 'itself', 'just', 'me', 'more', 'most', 'my',
    'myself', 'no', 'nor', 'not', 'now', 'of', 'off', 'on', 'once', 'only',
    'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'same',
    'she', 'should', 'so', 'some', 'such', 'than', 'that', 'the', 'their',
    'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', 'this',
    'those', 'through', 'to', 'too', 'under', 'until', 'up', 'very', 'was',
    'we', 'were', 'what', 'when', 'where', 'which', 'while', 'who', 'whom',
    'why', 'will', 'with', 'would', 'you', 'your', 'yours', 'yourself',
    'yourselves'
]);
